### PR TITLE
Moved Transaction into function newTransaction

### PR DESCRIPTION
**Pull request by carlosvdr**

### CODE REVIEW

**Review by aasseman — COMMENTED** [review]
:thinking: I'm not sure that moving everything related to `Transaction` into a function is really beneficial to readability.
Originally I was thinking that just moving `new Transaction(...` part would help with avoiding to to string manipulations every time.

**Comment by carlosvdr** [comment]
Not gonna lie I thought the same, its not actually helping, but thought just moving the string manipulation to a function wasn't making much a difference either @aasseman

**Comment by aasseman** [comment]
> Not gonna lie I thought the same, its not actually helping, but thought just moving the string manipulation to a function wasn't making much a difference either @aasseman, so decided to move more to make more sense of having a function but now it looks like it was better before too

OK, perhaps let's close this one then?

**Comment by carlosvdr** [comment]
Closing this, not really necessary

**Pull request closed without merging**
